/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Erc20Bytes32 } from "../Erc20Bytes32";

export class Erc20Bytes32__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Erc20Bytes32 {
    return new Contract(address, _abi, signerOrProvider) as Erc20Bytes32;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "name",
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "symbol",
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
